rm(list = ls())
root <- normalizePath(if (file.exists("R/load_all.R")) "." else "..")

fmt_ms <- function(x, digits = 3L) {
  x <- x[is.finite(x)]
  if (!length(x)) return("--")
  m <- mean(x)
  s <- if (length(x) > 1L) sd(x) else NA_real_
  if (is.finite(s)) {
    paste0(formatC(m, format = "f", digits = digits), " (",
           formatC(s, format = "f", digits = digits), ")")
  } else {
    formatC(m, format = "f", digits = digits)
  }
}

# Experiment 1 table: clustering metrics only; no BIC.
f1 <- file.path(root, "results", "experiment1_raw.csv")
if (file.exists(f1)) {
  d <- read.csv(f1, stringsAsFactors = FALSE)
  d <- d[d$Success, ]
  rows <- list()
  kappas <- sort(unique(d$Kappa))
  models <- c("DGMM", "RDMM", "DStMM")
  for (kap in kappas) for (model in models) {
    z <- d[d$Kappa == kap & d$Model == model, ]
    rows[[length(rows) + 1L]] <- c(
      as.character(kap), model,
      fmt_ms(z$Layer1_ARI), fmt_ms(z$Layer1_MR),
      fmt_ms(z$Pathway_ARI), fmt_ms(z$Pathway_MR)
    )
  }
  body <- vapply(rows, function(r) paste0(paste(r, collapse = " & "), " \\\\"), character(1))
  tex <- c(
    "% Auto-generated by scripts/50_export_latex_tables.R",
    "\\begin{table}[t]",
    "\\centering",
    "\\caption{Experiment 1 clustering results. Entries are Monte Carlo mean (standard deviation).}",
    "\\label{tab:exp1-results}",
    "\\begin{tabular}{ccrrrr}",
    "\\hline",
    "$\\kappa$ & Model & L1 ARI & L1 MR & Path ARI & Path MR \\\\",
    "\\hline",
    body,
    "\\hline",
    "\\end{tabular}",
    "\\end{table}"
  )
  writeLines(tex, file.path(root, "results", "table_experiment1.tex"))
}

# Experiment 2 table: clustering metrics only; no BIC.
f2 <- file.path(root, "results", "experiment2_raw.csv")
if (file.exists(f2)) {
  d <- read.csv(f2, stringsAsFactors = FALSE)
  d <- d[d$Success, ]
  rows <- list()
  nus <- sort(unique(d$Nu))
  kappas <- sort(unique(d$Kappa))
  models <- c("DGMM", "RDMM", "DStMM")
  for (nu in nus) for (kap in kappas) for (model in models) {
    z <- d[d$Nu == nu & d$Kappa == kap & d$Model == model, ]
    rows[[length(rows) + 1L]] <- c(
      as.character(nu), as.character(kap), model,
      fmt_ms(z$Layer1_ARI), fmt_ms(z$Layer1_MR),
      fmt_ms(z$Pathway_ARI), fmt_ms(z$Pathway_MR)
    )
  }
  body <- vapply(rows, function(r) paste0(paste(r, collapse = " & "), " \\\\"), character(1))
  tex <- c(
    "% Auto-generated by scripts/50_export_latex_tables.R",
    "\\begin{table}[t]",
    "\\centering",
    "\\caption{Experiment 2 clustering results. Entries are Monte Carlo mean (standard deviation).}",
    "\\label{tab:exp2-results}",
    "\\begin{tabular}{cccrrrr}",
    "\\hline",
    "$\\nu$ & $\\kappa$ & Model & L1 ARI & L1 MR & Path ARI & Path MR \\\\",
    "\\hline",
    body,
    "\\hline",
    "\\end{tabular}",
    "\\end{table}"
  )
  writeLines(tex, file.path(root, "results", "table_experiment2.tex"))
}

cat("LaTeX tables written to results/ without BIC columns.\n")
